on:
  push:
    branches:
      - master
name: Build & Deploy to ACI
env:
  LOCATION: centralindia
  RESOURCE_GROUP: ShareFreeAlphaARG
  KEY_VAULT: ShareFreeAlphaAKV
  CONTAINER_REGISTERY: sharefreealphaacr
  APP_NAME: share-free-messaging
  WEBAPP_NAME: sharefreemsgalpha
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout GitHub Action
          uses: actions/checkout@master
          
        - name: Login to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Set default location
          run: |
            az configure --defaults location=${{ env.LOCATION }}
            az configure --defaults group=${{ env.RESOURCE_GROUP }}

        - name: Get env Secrets
          run: |
            MONGO_DB_URL=$(az keyvault secret show --name "MONGO-DB-URL" --vault-name ${{ env.KEY_VAULT }} --query "value")
            echo 'MONGO_DB_URL='$MONGO_DB_URL >> $GITHUB_ENV
        
        - name: Update .env
          run: |
            touch .env
            echo 'MONGO_DB_URL='${{ env.MONGO_DB_URL }} >> .env
        
        - name: Create service-account.json
          run: |
            touch src/auth/service-account.json
            printf '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' >> src/auth/service-account.json
        
        - name: Build & Push
          uses: azure/docker-login@v1
          with:
            login-server: ${{ env.CONTAINER_REGISTERY }}.azurecr.io
            username: ${{ secrets.AZURE_USERNAME }}
            password: ${{ secrets.AZURE_PASSWORD }}
        - run: |
            docker build . -t ${{ env.APP_NAME }}:1.0.${{ github.run_number }}
            docker tag ${{ env.APP_NAME }}:1.0.${{ github.run_number }} ${{ env.CONTAINER_REGISTERY }}.azurecr.io/builds/${{ env.APP_NAME }}:1.0.${{ github.run_number }}
            docker push ${{ env.CONTAINER_REGISTERY }}.azurecr.io/builds/${{ env.APP_NAME }}:1.0.${{ github.run_number }}

        - uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.WEBAPP_NAME }}
            images: ${{ env.CONTAINER_REGISTERY }}.azurecr.io/builds/${{ env.APP_NAME }}:1.0.${{ github.run_number }}

        - name: logout
          run: |
            az logout
